# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 795f80f4347e2607283d7beba7c18030c01224990e490ea92fddb47d1161709e58bd222299b1311014b3ea3eeb7a984e14c6fd2737a67a1aa4b1727aa2af5972

test:
  secret_key_base: bc83a9cc0744f2305d1d5356d12056e031e072dae19eeeb0a0cca06918c22c503145d1a38c3a032ac9f2d17c9c77746c9f89e6b8338c8216424203cbe996aa33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
